
CREATE TABLE IF NOT EXISTS COUNTRIES (
NAME VARCHAR(255) PRIMARY KEY,
ISO2 VARCHAR(2)
);

CREATE TABLE IF NOT EXISTS CITIES (
NAME VARCHAR(255) PRIMARY KEY,
COUNTRY_ID VARCHAR(255),
 FOREIGN KEY (COUNTRY_ID)
      REFERENCES COUNTRIES (NAME)
);

CREATE TABLE IF NOT EXISTS CUSTOMERS (
ID VARCHAR(255) PRIMARY KEY,
NAME VARCHAR(255),
AGE INT,
ADDRESS VARCHAR(255),
ZIP_CODE VARCHAR(255),
CITY_ID VARCHAR(255),
 FOREIGN KEY (CITY_ID)
      REFERENCES CITIES (NAME)
);

CREATE TABLE IF NOT EXISTS CUSTOMER_PAYMENTS (
ID VARCHAR(255) PRIMARY KEY,
CUSTOMER_ID VARCHAR(255) NOT NULL,
IBAN VARCHAR(255),
CREDIT_CARD_NUMBER VARCHAR(255),
 FOREIGN KEY (CUSTOMER_ID)
      REFERENCES CUSTOMERS (ID)
);

CREATE TABLE IF NOT EXISTS ORDERS (
ID VARCHAR(255) PRIMARY KEY,
CUSTOMER_ID VARCHAR(255) NOT NULL,
PAYMENT_TYPE VARCHAR(255),
CREATION TIMESTAMP,
 FOREIGN KEY (CUSTOMER_ID)
      REFERENCES CUSTOMERS (ID)
);

CREATE TABLE IF NOT EXISTS CATEGORIES (
ID VARCHAR(255) PRIMARY KEY,
NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS SUB_CATEGORIES (
CATEGORY_ID VARCHAR(255) NOT NULL,
SUB_CATEGORY_ID VARCHAR(255) NOT NULL,
PRIMARY KEY (CATEGORY_ID, SUB_CATEGORY_ID),
 FOREIGN KEY (CATEGORY_ID)
    REFERENCES CATEGORIES (ID),
FOREIGN KEY (SUB_CATEGORY_ID)
    REFERENCES CATEGORIES (ID)
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
ID VARCHAR(255) PRIMARY KEY,
CATEGORY_ID VARCHAR(255) NOT NULL,
NAME VARCHAR(255),
DESCRIPTION VARCHAR(255),
PRICE DECIMAL,
 FOREIGN KEY (CATEGORY_ID)
      REFERENCES CATEGORIES (ID)
);

CREATE TABLE IF NOT EXISTS ORDER_PRODUCTS (
ORDER_ID VARCHAR(255) NOT NULL,
PRODUCT_ID VARCHAR(255) NOT NULL,
PRIMARY KEY (ORDER_ID, PRODUCT_ID),
 FOREIGN KEY (ORDER_ID)
      REFERENCES ORDERS (ID),
 FOREIGN KEY (PRODUCT_ID)
      REFERENCES PRODUCTS (ID)
);
